const CACHE='school20-pwa-v16';
const SHELL=['./','index.html','schedule.html','staff.html','style.css','site-schedule.css','staff.css','config.js','content.js','app.js','schedule.js','staff.js','school-day.js','assets/school-logo.jpg'];
const STATUS_URL='https://sheets.googleapis.com/v4/spreadsheets/1Va5atMLtrqb9JEXE7d9eytoTUFgN-lwT0xlYOevm4S4/values/%D0%A1%D1%82%D0%B0%D1%82%D1%83%D1%81_%D0%BF%D1%83%D0%B1%D0%BB%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%B8!A:F?key=AIzaSyDGhaQXvcEv-QvHRDHP_8Q9gVEvzd6fuFI';
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL).catch(()=>{})));self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim();});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy)).catch(()=>{});return r;}).catch(()=>caches.match(e.request).then(r=>r||caches.match('./'))));});
async function checkStatus(){try{const r=await fetch(STATUS_URL,{cache:'no-store'});if(!r.ok)return;const j=await r.json(),values=j.values||[];if(values.length<2)return;const latest=JSON.stringify(values[values.length-1]);const c=await caches.open(CACHE),oldResp=await c.match('__status__'),old=oldResp?await oldResp.text():'';await c.put('__status__',new Response(latest));if(old&&old!==latest)await self.registration.showNotification('МОУ СОШ № 20',{body:'Опубликованы новые изменения в расписании.',icon:'assets/school-logo.jpg',badge:'assets/school-logo.jpg',tag:'school20-changes',data:{url:'schedule.html#changes'}});}catch(_){}}
self.addEventListener('periodicsync',e=>{if(e.tag==='school20-changes-sync')e.waitUntil(checkStatus());});
self.addEventListener('sync',e=>{if(e.tag==='school20-changes-sync')e.waitUntil(checkStatus());});
self.addEventListener('message',e=>{if(e.data?.type==='CHECK_CHANGES')e.waitUntil(checkStatus());});
self.addEventListener('notificationclick',e=>{e.notification.close();const url=e.notification.data?.url||'schedule.html#changes';e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{const found=ws.find(w=>w.url.includes('sosh20tver.ru'));if(found){found.navigate(url);return found.focus();}return clients.openWindow(url);}));});
