(()=>{
'use strict';
const site=window.SchoolSite;if(!site)return;
const BELLS=[['08:00','08:40'],['08:50','09:30'],['09:45','10:25'],['10:45','11:25'],['11:40','12:20'],['12:30','13:10'],['13:20','14:00'],['14:15','14:55'],['15:10','15:50'],['16:05','16:45'],['17:00','17:40'],['17:50','18:30']];
const DAY_CODES=['ВС','ПН','ВТ','СР','ЧТ','ПТ','СБ'];
const esc=site.escapeHtml;
const fullSubject=v=>window.SchoolSubjects?.expandSubject?window.SchoolSubjects.expandSubject(v):String(v??'');
let cards=[],pageIndex=0,pageTimer=null;
function ensureRuntimeStyles(){if(document.querySelector('#teacher-tv-runtime-fixes'))return;const s=document.createElement('style');s.id='teacher-tv-runtime-fixes';s.textContent=`.lesson.is-current{padding-right:78px!important}.lesson.is-current:after{top:50%!important;right:7px!important;transform:translateY(-50%)!important;z-index:7!important}.lesson.is-current .room,.lesson.is-current .badge{position:relative;z-index:2}@media(max-width:1050px){.lesson.is-current{padding-right:70px!important}}`;document.head.appendChild(s)}
function todayIso(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Moscow'}).format(new Date())}
function normalizeDate(v){const s=String(v||'').trim(),m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:s.slice(0,10)}
function currentDayCode(){const d=new Date(),parts=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Moscow',weekday:'short'}).format(d);return({Mon:'ПН',Tue:'ВТ',Wed:'СР',Thu:'ЧТ',Fri:'ПТ',Sat:'СБ',Sun:'ВС'})[parts]||DAY_CODES[d.getUTCDay()]}
function pageSize(){if(innerWidth<=700)return 1;if(innerWidth<=1050)return 4;return 6}
function toMin(v){const[a,b]=String(v).split(':').map(Number);return a*60+b}
function momentState(){const s=new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()),[h,m]=s.split(':').map(Number),n=h*60+m;for(let i=0;i<BELLS.length;i++){const a=toMin(BELLS[i][0]),b=toMin(BELLS[i][1]);if(n>=a&&n<b)return{type:'lesson',lesson:i+1,remaining:b-n};if(n<a)return i?{type:'break',prev:i,next:i+1,remaining:a-n}:{type:'before',next:1,remaining:a-n}}return{type:'after'}}
function tick(){const d=new Date(),t=new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d),date=new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(d),state=momentState();document.querySelector('#time').textContent=t.slice(0,5);document.querySelector('#date').textContent=date;let text='Учебный день завершён';if(state.type==='lesson')text=`Идёт ${state.lesson}-й урок · до звонка ${state.remaining} мин`;else if(state.type==='break')text=`Перемена · ${state.next}-й урок через ${state.remaining} мин`;else if(state.type==='before')text=`До начала · 1-й урок через ${state.remaining} мин`;document.querySelector('#countdown').textContent=text;document.querySelectorAll('.lesson').forEach(el=>{const n=Number(el.dataset.lesson);el.classList.toggle('is-current',state.type==='lesson'&&n===state.lesson);el.classList.toggle('break-after',state.type==='break'&&n===state.prev)})}
function parseBaseCell(v){const s=String(v??'').trim();if(!s)return null;const p=s.split('|').map(x=>x.trim());if(p.length>=2)return{cls:p[0]||'',subj:fullSubject(p[1]||''),room:p.slice(2).join('|').trim()};const m=s.match(/^([^·]+?)\s*[·-]\s*([^·]+?)(?:\s*[·-]\s*(.+))?$/);return m?{cls:m[1].trim(),subj:fullSubject(m[2].trim()),room:String(m[3]||'').trim()}:{cls:'',subj:fullSubject(s),room:''}}
function teacherBase(rows){if(!Array.isArray(rows)||!rows.length)return{order:[],map:new Map()};const headers=rows[0].map(x=>String(x||'').trim()),hasHeader=site.looksLikeHeader(rows[0],['фио','урок','пн','понедельник']),data=hasHeader?rows.slice(1):rows,hs=hasHeader?headers:['ФИО','УРОК','ПН','ВТ','СР','ЧТ','ПТ'],day=currentDayCode(),dayIndex=hs.findIndex(h=>String(h).toUpperCase()===day),teacherIndex=Math.max(0,hs.findIndex(h=>/фио|учитель/i.test(h))),lessonIndex=Math.max(1,hs.findIndex(h=>/урок/i.test(h))),order=[],map=new Map();data.forEach(r=>{const teacher=String(r[teacherIndex]||'').trim(),lesson=Number(String(r[lessonIndex]||'').match(/\d+/)?.[0]||0);if(!teacher||!lesson)return;if(!map.has(teacher)){map.set(teacher,new Map());order.push(teacher)}const cell=dayIndex>=0?parseBaseCell(r[dayIndex]):null;if(cell)map.get(teacher).set(lesson,{lesson,...cell,status:'normal'})});return{order,map}}
function changeType(status){const s=String(status||'').toLowerCase();if(/cancel|отмен/.test(s))return'cancelled';if(/room|кабин/.test(s))return'room-change';if(/add|добав/.test(s))return'added';return'changed'}
function overlayChanges(base,rows){const today=todayIso();if(!Array.isArray(rows)||rows.length<2)return base;const d=rows.slice(1),ix={date:0,teacher:1,lesson:2,cls:3,subj:4,room:5,status:6,oldCls:7,oldSubj:8,oldRoom:9};d.filter(r=>normalizeDate(r[ix.date])===today&&String(r[ix.status]||'normal')!=='normal').forEach(r=>{const teacher=String(r[ix.teacher]||'').trim(),lesson=Number(r[ix.lesson])||0;if(!teacher||!lesson)return;if(!base.map.has(teacher)){base.map.set(teacher,new Map());base.order.push(teacher)}const current=base.map.get(teacher).get(lesson)||null,type=changeType(r[ix.status]);const old={cls:String(r[ix.oldCls]||current?.cls||''),subj:fullSubject(String(r[ix.oldSubj]||current?.subj||'')),room:String(r[ix.oldRoom]||current?.room||'')};const next={cls:String(r[ix.cls]||current?.cls||''),subj:fullSubject(String(r[ix.subj]||current?.subj||'')),room:String(r[ix.room]||current?.room||'')};base.map.get(teacher).set(lesson,{lesson,status:type,old,next,cls:next.cls,subj:next.subj,room:next.room})});return base}
function hasActiveLessons(map){if(!(map instanceof Map)||!map.size)return false;return[...map.values()].some(x=>{const status=String(x.status||'normal');if(status==='cancelled')return false;const n=x.next||{};return Boolean(String(x.cls||n.cls||'').trim()||String(x.subj||n.subj||'').trim()||String(x.room||n.room||'').trim())})}
function statusLabel(s){return({cancelled:'ОТМЕНЕНО',changed:'ИЗМЕНЕНО','room-change':'КАБИНЕТ',added:'ДОБАВЛЕНО'})[s]||''}
function summary(items){const c={cancelled:0,changed:0,'room-change':0,added:0};items.forEach(x=>{if(x.status!=='normal')c[x.status]=(c[x.status]||0)+1});const total=Object.values(c).reduce((a,b)=>a+b,0);if(!total)return'';return`<div class="summary"><span>${total} изм.</span>${c.cancelled?`<span class="red">отм. ${c.cancelled}</span>`:''}${c.changed?`<span class="blue">зам. ${c.changed}</span>`:''}${c['room-change']?`<span class="amber">каб. ${c['room-change']}</span>`:''}${c.added?`<span class="green">добав. ${c.added}</span>`:''}</div>`}
function rowHtml(x){const time=BELLS[x.lesson-1]?.[0]||'',status=x.status||'normal';if(status==='normal')return`<div class="lesson" data-lesson="${x.lesson}"><span class="num">${x.lesson}</span><span class="time">${esc(time)}</span><span class="cls">${esc(x.cls||'')}</span><span class="lesson-main"><strong>${esc(fullSubject(x.subj||''))}</strong></span><span class="room">${esc(x.room||'')}</span></div>`;if(status==='cancelled'){const o=x.old||{};return`<div class="lesson cancelled" data-lesson="${x.lesson}"><span class="num">${x.lesson}</span><span class="time">${esc(time)}</span><span class="cls">${esc(o.cls||'')}</span><span class="lesson-main"><del>${esc([fullSubject(o.subj||''),o.room].filter(Boolean).join(' · ')||'Урок')}</del></span><em class="badge">ОТМЕНЕНО</em></div>`}if(status==='room-change'){const o=x.old||{},n=x.next||{};return`<div class="lesson room-change" data-lesson="${x.lesson}"><span class="num">${x.lesson}</span><span class="time">${esc(time)}</span><span class="cls">${esc(n.cls||o.cls||'')}</span><span class="lesson-main"><strong>${esc(fullSubject(n.subj||o.subj||''))}</strong><small>${esc(o.room||'—')} → ${esc(n.room||'—')}</small></span><em class="badge">КАБИНЕТ</em></div>`}const o=x.old||{},n=x.next||{};return`<div class="lesson ${status}" data-lesson="${x.lesson}"><span class="num">${x.lesson}</span><span class="time">${esc(time)}</span><span class="cls">${esc(n.cls||o.cls||'')}</span><span class="lesson-main">${o.subj||o.cls||o.room?`<del>${esc([o.cls,fullSubject(o.subj||''),o.room].filter(Boolean).join(' · '))}</del>`:''}<strong>${esc([n.cls,fullSubject(n.subj||''),n.room].filter(Boolean).join(' · '))}</strong></span><em class="badge">${statusLabel(status)}</em></div>`}
function cardHtml(teacher,map){const items=[...map.values()].sort((a,b)=>a.lesson-b.lesson);return`<article class="teacher-card"><header><h2 title="${esc(teacher)}">${esc(teacher)}</h2>${summary(items)}</header><div class="teacher-lessons">${items.length?items.map(rowHtml).join(''):'<div class="empty-card">Сегодня уроков нет</div>'}</div></article>`}
function renderPage(){const el=document.querySelector('#teachers'),size=pageSize(),pages=Math.max(1,Math.ceil(cards.length/size));if(pageIndex>=pages)pageIndex=0;const slice=cards.slice(pageIndex*size,pageIndex*size+size);el.classList.remove('page-enter');void el.offsetWidth;el.classList.add('page-enter');el.innerHTML=slice.length?slice.join(''):'<div class="empty-card">Сегодня нет учителей с действующими уроками.</div>';document.querySelector('#page').textContent=pages>1?`Страница ${pageIndex+1} из ${pages} · следующая через 10 сек`:'Все учителя помещаются на одном экране';document.querySelector('#progress').style.width=pages>1?`${((pageIndex+1)/pages)*100}%`:'100%';tick()}
function resetRotation(){if(pageTimer)clearInterval(pageTimer);renderPage();const pages=Math.ceil(cards.length/pageSize());if(pages>1)pageTimer=setInterval(()=>{pageIndex=(pageIndex+1)%pages;renderPage()},10000)}
async function load(){try{const[baseRows,changeRows]=await Promise.all([site.loadSheet('Учителя',{force:true,optional:true}),site.loadSheet('Учителя_сайт',{force:true,optional:true})]),data=overlayChanges(teacherBase(baseRows||[]),changeRows||[]);cards=data.order.filter(t=>hasActiveLessons(data.map.get(t))).map(t=>cardHtml(t,data.map.get(t)));pageIndex=0;resetRotation();await notices();document.querySelector('#updated').textContent=new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'}).format(new Date())}catch(e){cards=['<div class="empty-card">Не удалось обновить расписание. Проверьте подключение к сети.</div>'];pageIndex=0;resetRotation()}}
async function notices(){try{const rows=await site.loadSheet('Оповещения',{force:true,optional:true}),today=todayIso(),r=rows?.slice(1).reverse().find(x=>{const a=String(x[11]||'all');return String(x[12]||'true').toLowerCase()!=='false'&&['all','teachers'].includes(a)&&(!normalizeDate(x[5])||normalizeDate(x[5])<=today)&&(!normalizeDate(x[6])||normalizeDate(x[6])>=today)});document.querySelector('#notice').innerHTML=r?`<div class="notice"><strong>${esc(r[2]||'')}</strong>${r[3]?'<span>'+esc(r[3])+'</span>':''}</div>`:''}catch(_){}}
ensureRuntimeStyles();tick();setInterval(tick,15000);load();setInterval(load,60000);addEventListener('resize',resetRotation);
})();
