import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const MAX_API=process.env.MAX_API_BASE||'https://platform-api2.max.ru';
const BOT_TOKEN=String(process.env.BOT_TOKEN||'').trim();
const SITE_URL=String(process.env.SCHOOL_SITE_URL||'https://sosh20tver.ru').replace(/\/$/,'');
const SITE_CONFIG_URL=process.env.SITE_CONFIG_URL||`${SITE_URL}/config.js`;
const APPS_SCRIPT_URL=String(process.env.APPS_SCRIPT_URL||'https://script.google.com/macros/s/AKfycbzE-k5KDPobjb32ySdEU6vRqvrxLETV_ktJHPn1LnWdp1pZX-t0WL3L4pyA576oe9S1Sg/exec').trim();
const DATA_FILE=process.env.DATA_FILE||'/app/data/state.json';
const CHECK_SECONDS=Math.max(15,Number(process.env.CHECK_SECONDS||30));
const TZ='Europe/Moscow';
if(!BOT_TOKEN){console.error('BOT_TOKEN is required');process.exit(1)}

const state=loadState();let sheetConfig=null,sheetCache=new Map(),stopping=false;
function loadState(){try{const p=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'));return{profiles:p.profiles||{},marker:p.marker??null,delivery:p.delivery||{},noticeSeen:p.noticeSeen||{},confirmations:p.confirmations||{},notificationPrimed:!!p.notificationPrimed}}catch{return{profiles:{},marker:null,delivery:{},noticeSeen:{},confirmations:{},notificationPrimed:false}}}
function saveState(){fs.mkdirSync(path.dirname(DATA_FILE),{recursive:true});const tmp=DATA_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(state,null,2));fs.renameSync(tmp,DATA_FILE)}
function log(...a){console.log(new Intl.DateTimeFormat('ru-RU',{timeZone:TZ,hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date()),...a)}
const esc=v=>String(v??'').replace(/([*_`\[\]])/g,'\\$1');
const hash=v=>crypto.createHash('sha1').update(JSON.stringify(v)).digest('hex').slice(0,16);
function moscowIso(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),m=Object.fromEntries(p.map(x=>[x.type,x.value]));return`${m.year}-${m.month}-${m.day}`}
function addDays(iso,n){const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
const ruDate=iso=>{const[y,m,d]=iso.split('-');return`${d}.${m}.${y}`};
const dayCode=iso=>['ВС','ПН','ВТ','СР','ЧТ','ПТ','СБ'][new Date(`${iso}T12:00:00Z`).getUTCDay()];
const dayName=iso=>new Intl.DateTimeFormat('ru-RU',{timeZone:'UTC',weekday:'long',day:'numeric',month:'long'}).format(new Date(`${iso}T12:00:00Z`));
const normClass=v=>String(v||'').trim().toUpperCase().replace(/Ё/g,'Е').replace(/\s+/g,'');
function normDate(v){const s=String(v||'').trim();let m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})$/);if(m)return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:''}
const cb=(text,payload)=>({type:'callback',text,payload});
const link=(text,url)=>({type:'link',text,url});
const keyboard=rows=>[{type:'inline_keyboard',payload:{buttons:rows}}];
function hidx(h,names,f=-1){const n=v=>String(v||'').trim().toLowerCase().replace(/ё/g,'е').replace(/[\s_\-–—.():№]+/g,'');const a=h.map(n);for(const x of names){const i=a.indexOf(n(x));if(i>=0)return i}return f}
async function max(method,ep,body){const r=await fetch(MAX_API+ep,{method,headers:{Authorization:BOT_TOKEN,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={raw:t}}if(!r.ok)throw new Error(`MAX ${r.status}: ${t.slice(0,250)}`);return d}
async function send(uid,text,buttons=[],notify=true){const b={text:String(text).slice(0,4000),format:'markdown',notify};if(buttons.length)b.attachments=keyboard(buttons);return max('POST',`/messages?user_id=${encodeURIComponent(uid)}`,b)}
async function answer(id,text,buttons=[]){const m={text:String(text).slice(0,4000),format:'markdown'};if(buttons.length)m.attachments=keyboard(buttons);return max('POST',`/answers?callback_id=${encodeURIComponent(id)}`,{message:m})}
async function siteCfg(){if(sheetConfig)return sheetConfig;let spreadsheetId=String(process.env.SPREADSHEET_ID||'').trim(),apiKey=String(process.env.SHEETS_API_KEY||'').trim();if(!spreadsheetId||!apiKey){const r=await fetch(SITE_CONFIG_URL,{cache:'no-store'});if(!r.ok)throw new Error('Не загружается config.js сайта');const js=await r.text();spreadsheetId||=js.match(/spreadsheetId\s*:\s*['"]([^'"]+)['"]/)?.[1]||'';apiKey||=js.match(/apiKey\s*:\s*['"]([^'"]+)['"]/)?.[1]||''}if(!spreadsheetId||!apiKey)throw new Error('Не найдены настройки Google Sheets');return sheetConfig={spreadsheetId,apiKey}}
async function sheet(name,ttl=10000){const c=sheetCache.get(name);if(c&&Date.now()-c.at<ttl)return c.rows;const{spreadsheetId,apiKey}=await siteCfg(),u=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(spreadsheetId)}/values/${encodeURIComponent(name)}?key=${encodeURIComponent(apiKey)}`,r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(`Google Sheets ${name}: ${r.status}`);const d=await r.json(),rows=Array.isArray(d.values)?d.values:[];sheetCache.set(name,{at:Date.now(),rows});return rows}
async function classes(){const r=await sheet('Расписание');if(!r.length)return[];const ci=hidx(r[0],['Класс'],0),a=[];r.slice(1).forEach(x=>{const c=normClass(x[ci]);if(c&&!a.includes(c)&&/^(?:[5-9]|10|11)[А-Я]$/.test(c))a.push(c)});return a.sort((a,b)=>a.localeCompare(b,'ru',{numeric:true}))}
async function teachers(){const r=await sheet('Учителя');if(!r.length)return[];const ti=hidx(r[0],['ФИО','Учитель'],0),a=[];r.slice(1).forEach(x=>{const t=String(x[ti]||'').trim();if(t&&!a.includes(t))a.push(t)});return a}
function parseTC(v){const s=String(v||'').trim();if(!s)return{className:'',subject:'',room:''};const p=s.split(/\r?\n|\s*\|\s*/).map(x=>x.trim()).filter(Boolean);return p.length>=2?{className:normClass(p[0]),subject:p[1]||'',room:p[2]||''}:{className:normClass(s),subject:'',room:''}}
function parseST(v){const s=String(v||'').trim(),m=s.match(/^(.*?)\s*\(([^()]*)\)\s*$/);return m?{subject:m[1].trim(),room:m[2].trim()}:{subject:s,room:''}}
async function baseStudent(date,cls){const r=await sheet('Расписание');if(!r.length)return[];const h=r[0],ci=hidx(h,['Класс'],0),li=hidx(h,['Урок'],1),di=h.map(x=>String(x||'').trim().toUpperCase()).indexOf(dayCode(date));if(di<0)return[];return r.slice(1).filter(x=>normClass(x[ci])===normClass(cls)).map(x=>{const p=parseST(x[di]);return{lesson:Number(x[li])||0,subject:p.subject,room:p.room}}).filter(x=>x.lesson>=1&&x.lesson<=12&&x.subject).sort((a,b)=>a.lesson-b.lesson)}
async function studentChanges(date,cls){const r=await sheet('Изменения',5000);if(!r.length)return[];const h=r[0],di=hidx(h,['Дата'],0),ci=hidx(h,['Класс'],1),li=hidx(h,['Урок'],2),xi=hidx(h,['Изменение'],3),ni=hidx(h,['Примечание'],4);return r.slice(1).filter(x=>normDate(x[di])===date&&normClass(x[ci])===normClass(cls)).map(x=>({lesson:Number(x[li])||0,change:String(x[xi]||'').trim(),note:String(x[ni]||'').trim()})).filter(x=>x.lesson&&x.change).sort((a,b)=>a.lesson-b.lesson)}
async function studentDay(date,cls){const m=new Map((await baseStudent(date,cls)).map(x=>[x.lesson,{...x,status:'normal'}]));for(const x of await studentChanges(date,cls)){if(/^отмена$/i.test(x.change))m.set(x.lesson,{lesson:x.lesson,subject:'ОТМЕНА',room:'',status:'cancelled',note:x.note});else{const p=parseST(x.change);m.set(x.lesson,{lesson:x.lesson,subject:p.subject||x.change,room:p.room,status:'changed',note:x.note})}}return[...m.values()].sort((a,b)=>a.lesson-b.lesson)}
async function baseTeacher(date,t){const r=await sheet('Учителя');if(!r.length)return[];const h=r[0],ti=hidx(h,['ФИО','Учитель'],0),li=hidx(h,['УРОК','Урок'],1),di=h.map(x=>String(x||'').trim().toUpperCase()).indexOf(dayCode(date));if(di<0)return[];return r.slice(1).filter(x=>String(x[ti]||'').trim()===t).map(x=>{const p=parseTC(x[di]);return{lesson:Number(x[li])||0,className:p.className,subject:p.subject,room:p.room,status:'normal',oldClass:'',oldSubject:'',oldRoom:''}}).filter(x=>x.lesson>=1&&x.lesson<=12&&x.className).sort((a,b)=>a.lesson-b.lesson)}
async function publicTeacher(date,t){const r=await sheet('Учителя_сайт',5000);if(!r.length)return[];const h=r[0],i={d:hidx(h,['Дата'],0),t:hidx(h,['Учитель'],1),l:hidx(h,['Урок'],2),c:hidx(h,['Класс'],3),s:hidx(h,['Предмет'],4),r:hidx(h,['Кабинет'],5),st:hidx(h,['Статус'],6),oc:hidx(h,['Было_класс'],7),os:hidx(h,['Было_предмет'],8),or:hidx(h,['Было_кабинет'],9),n:hidx(h,['Примечание'],10)};return r.slice(1).filter(x=>normDate(x[i.d])===date&&String(x[i.t]||'').trim()===t).map(x=>({lesson:Number(x[i.l])||0,className:normClass(x[i.c]),subject:String(x[i.s]||'').trim(),room:String(x[i.r]||'').trim(),status:String(x[i.st]||'normal').trim()||'normal',oldClass:normClass(x[i.oc]),oldSubject:String(x[i.os]||'').trim(),oldRoom:String(x[i.or]||'').trim(),note:String(x[i.n]||'').trim()})).filter(x=>x.lesson>=1&&x.lesson<=12).sort((a,b)=>a.lesson-b.lesson)}
async function teacherDay(date,t){const p=await publicTeacher(date,t);return p.length?p:baseTeacher(date,t)}
async function teacherChanges(date,t){return(await publicTeacher(date,t)).filter(x=>x.status!=='normal')}
async function notices(audience){const r=await sheet('Оповещения',5000);if(!r.length)return[];const today=moscowIso(),h=r[0],i={id:hidx(h,['ID'],0),title:hidx(h,['Заголовок'],2),text:hidx(h,['Текст'],3),level:hidx(h,['Тип'],4),start:hidx(h,['Начало'],5),end:hidx(h,['Окончание'],6),files:hidx(h,['Файлы JSON'],8),button:hidx(h,['Текст кнопки'],9),url:hidx(h,['Ссылка'],10),aud:hidx(h,['Аудитория'],11),active:hidx(h,['Активно'],12)};return r.slice(1).filter(x=>{const s=normDate(x[i.start]),e=normDate(x[i.end]),a=String(x[i.aud]||'all'),on=String(x[i.active]??'true').toLowerCase()!=='false';return on&&(!s||s<=today)&&(!e||e>=today)&&(a==='all'||a===audience)}).map(x=>{let f=[];try{f=JSON.parse(String(x[i.files]||'[]'))}catch{}return{id:String(x[i.id]||''),title:String(x[i.title]||''),text:String(x[i.text]||''),level:String(x[i.level]||'info'),files:f,buttonText:String(x[i.button]||''),url:String(x[i.url]||'')}})}
function menu(p){if(!p?.role)return[[cb('Учитель','role:teacher')],[cb('Ученик / родитель','role:student')]];return[[cb('Сегодня','today'),cb('Завтра','tomorrow')],[cb(p.role==='teacher'?'Мои изменения':'Изменения','changes'),cb('Оповещения','notices')],[cb('Профиль','profile')]]}
const profileLabel=p=>!p?.role?'не настроен':p.role==='teacher'?`Учитель: ${p.teacher||'не выбран'}`:`Класс: ${p.className||'не выбран'}`;
function ensureProfile(uid,u={},chat=''){const o=state.profiles[uid]||{};state.profiles[uid]={...o,userId:String(uid),chatId:String(chat||o.chatId||uid),name:[u.first_name,u.last_name].filter(Boolean).join(' ')||o.name||'',notifications:o.notifications!==false,createdAt:o.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};saveState();return state.profiles[uid]}
async function home(uid,cid=''){const p=state.profiles[uid],t=p?.role?`**СОШ №20 · Расписание**\n${esc(profileLabel(p))}\n\nВыберите действие:`:'**СОШ №20 · Расписание**\n\nКто вы? Настройка займёт несколько секунд.';return cid?answer(cid,t,menu(p)):send(uid,t,menu(p))}
async function pickTeacher(uid,cid,page=0){const a=await teachers(),n=8,pages=Math.max(1,Math.ceil(a.length/n));page=Math.max(0,Math.min(page,pages-1));const rows=a.slice(page*n,page*n+n).map((t,j)=>[cb(t.split(' ')[0],`teacher:${page*n+j}`)]),nav=[];if(page>0)nav.push(cb('←',`teacherpage:${page-1}`));nav.push(cb(`${page+1}/${pages}`,`teacherpage:${page}`));if(page<pages-1)nav.push(cb('→',`teacherpage:${page+1}`));rows.push(nav,[cb('Назад','profile')]);return answer(cid,'**Выберите преподавателя**\nПорядок фамилий — как в школьном расписании.',rows)}
async function pickClass(uid,cid){const a=await classes(),rows=[];for(let i=0;i<a.length;i+=3)rows.push(a.slice(i,i+3).map((c,j)=>cb(c,`class:${i+j}`)));rows.push([cb('Назад','profile')]);return answer(cid,'**Выберите класс**',rows)}
async function profile(uid,cid){const p=state.profiles[uid],t=`**Профиль**\n${esc(profileLabel(p))}\n\nАвтоматические уведомления: ${p?.notifications===false?'выключены':'включены'}`,rows=p?.role==='teacher'?[[cb('Сменить учителя','role:teacher')],[cb(p.notifications===false?'Включить уведомления':'Выключить уведомления','toggle_notify')],[cb('Сменить роль','reset_role')],[cb('Главное меню','home')]]:p?.role==='student'?[[cb('Сменить класс','role:student')],[cb(p.notifications===false?'Включить уведомления':'Выключить уведомления','toggle_notify')],[cb('Сменить роль','reset_role')],[cb('Главное меню','home')]]:[[cb('Учитель','role:teacher')],[cb('Ученик / родитель','role:student')],[cb('Главное меню','home')]];return answer(cid,t,rows)}
async function showDay(uid,date,cid=''){const p=state.profiles[uid];if(!p?.role)return home(uid,cid);let t=`**${dayName(date)}**\n`;if(p.role==='teacher'){const a=await teacherDay(date,p.teacher);t+=`_${esc(p.teacher)}_\n\n`+(a.length?a.map(x=>x.status==='cancelled'?`**${x.lesson}.** ~~${esc(x.oldClass||'')} ${esc(x.oldSubject||'')}~~ → **ОКНО**`:`**${x.lesson}.** ${x.status!=='normal'?'⚠ ':''}${esc(x.className)} · ${esc(x.subject||'')}${x.room?` · каб. ${esc(x.room)}`:''}`).join('\n'):'Уроков нет.')}else{const a=await studentDay(date,p.className);t+=`_${esc(p.className)}_\n\n`+(a.length?a.map(x=>x.status==='cancelled'?`**${x.lesson}. ОТМЕНА**`:`**${x.lesson}.** ${x.status!=='normal'?'⚠ ':''}${esc(x.subject)}${x.room?` · каб. ${esc(x.room)}`:''}`).join('\n'):'Уроков нет.')}const b=[[cb('← Главное','home'),cb(date===moscowIso()?'Завтра':'Сегодня',date===moscowIso()?'tomorrow':'today')],[link('Открыть сайт',p.role==='teacher'?`${SITE_URL}/staff.html`:`${SITE_URL}/schedule.html#changes`)]];return cid?answer(cid,t,b):send(uid,t,b)}
async function showChanges(uid,cid=''){const p=state.profiles[uid];if(!p?.role)return home(uid,cid);const d=moscowIso();let t=`**Изменения на ${ruDate(d)}**\n\n`;if(p.role==='teacher'){const a=await teacherChanges(d,p.teacher);t+=a.length?a.map(x=>x.status==='cancelled'?`**${x.lesson} урок** — ОКНО${x.oldClass?` · было ${esc(x.oldClass)} ${esc(x.oldSubject||'')}`:''}`:`**${x.lesson} урок** — ${esc(x.className)} · ${esc(x.subject||'')}${x.room?` · каб. ${esc(x.room)}`:''}`).join('\n'):'Для вас изменений нет.'}else{const a=await studentChanges(d,p.className);t+=a.length?a.map(x=>`**${x.lesson} урок** — ${esc(x.change)}${x.note?` · ${esc(x.note)}`:''}`).join('\n'):`Для ${esc(p.className)} изменений нет.`}const b=[[cb('Сегодня','today'),cb('Главное меню','home')]];return cid?answer(cid,t,b):send(uid,t,b)}
async function showNotices(uid,cid=''){const p=state.profiles[uid],a=await notices(p?.role==='teacher'?'teachers':'students');let t='**Оповещения школы**\n\n'+(a.length?a.slice(-5).reverse().map(n=>`**${esc(n.title||'Сообщение')}**\n${esc(n.text||'')}`).join('\n\n'):'Активных оповещений нет.'),rows=[],n=a.at(-1);if(n?.url)rows.push([link(n.buttonText||'Подробнее',n.url)]);else if(n?.files?.[0]?.url)rows.push([link('Открыть файл',n.files[0].url)]);rows.push([cb('Главное меню','home')]);return cid?answer(cid,t,rows):send(uid,t,rows)}
function context(u){const m=u.message||u.callback?.message||{},user=u.user||u.callback?.user||m.sender||{},uid=String(user.user_id||u.chat_id||m.recipient?.user_id||''),chat=String(u.chat_id||m.recipient?.chat_id||uid||''),text=String(m.body?.text||m.text||'').trim();return{user,uid,chat,text}}
async function seen(date,teacher,uid){if(!APPS_SCRIPT_URL)return;const b=new URLSearchParams({action:'markSeen',date,teacher,device:`max:${uid}`}),r=await fetch(APPS_SCRIPT_URL,{method:'POST',body:b,redirect:'follow'});if(!r.ok)throw new Error(`Apps Script ${r.status}`)}
async function onCallback(u){const{user,uid,chat}=context(u);if(!uid)return;ensureProfile(uid,user,chat);const id=u.callback?.callback_id||'',p=String(u.callback?.payload||'');if(p==='home')return home(uid,id);if(p==='role:teacher')return pickTeacher(uid,id,0);if(p==='role:student')return pickClass(uid,id);if(p.startsWith('teacherpage:'))return pickTeacher(uid,id,Number(p.split(':')[1])||0);if(p.startsWith('teacher:')){const a=await teachers(),t=a[Number(p.split(':')[1])];if(!t)return pickTeacher(uid,id,0);state.profiles[uid]={...state.profiles[uid],role:'teacher',teacher:t,className:'',updatedAt:new Date().toISOString()};saveState();return answer(id,`**Профиль сохранён**\nУчитель: ${esc(t)}`,menu(state.profiles[uid]))}if(p.startsWith('class:')){const a=await classes(),c=a[Number(p.split(':')[1])];if(!c)return pickClass(uid,id);state.profiles[uid]={...state.profiles[uid],role:'student',className:c,teacher:'',updatedAt:new Date().toISOString()};saveState();return answer(id,`**Профиль сохранён**\nКласс: ${esc(c)}`,menu(state.profiles[uid]))}if(p==='today')return showDay(uid,moscowIso(),id);if(p==='tomorrow')return showDay(uid,addDays(moscowIso(),1),id);if(p==='changes')return showChanges(uid,id);if(p==='notices')return showNotices(uid,id);if(p==='profile')return profile(uid,id);if(p==='toggle_notify'){state.profiles[uid].notifications=state.profiles[uid].notifications===false;saveState();return profile(uid,id)}if(p==='reset_role'){delete state.profiles[uid].role;delete state.profiles[uid].teacher;delete state.profiles[uid].className;saveState();return home(uid,id)}if(p.startsWith('seen:')){const d=p.slice(5),pr=state.profiles[uid];if(pr?.role==='teacher'&&pr.teacher){await seen(d,pr.teacher,uid).catch(e=>log('seen:',e.message));state.confirmations[`${uid}|${d}`]=new Date().toISOString();saveState()}const old=String(u.callback?.message?.body?.text||'Изменения в расписании');return answer(id,`${old}\n\n✓ **Просмотрено и подтверждено**`,[[cb('Сегодня','today'),cb('Главное меню','home')]])}return home(uid,id)}
async function onCommand(uid,text){const c=text.toLowerCase().trim().split(/\s+/)[0];if(['/start','/help','меню','menu'].includes(c))return home(uid);if(c==='/today')return showDay(uid,moscowIso());if(c==='/tomorrow')return showDay(uid,addDays(moscowIso(),1));if(c==='/changes')return showChanges(uid);if(c==='/profile')return send(uid,`Профиль: ${profileLabel(state.profiles[uid])}`,[[cb('Открыть профиль','profile')],[cb('Главное меню','home')]]);return home(uid)}
async function onUpdate(u){const{user,uid,chat,text}=context(u);if(!uid||user?.is_bot)return;ensureProfile(uid,user,chat);if(u.update_type==='bot_started')return home(uid);if(u.update_type==='message_callback')return onCallback(u);if(u.update_type==='message_created')return onCommand(uid,text||'/start')}
async function poll(){log('Long polling started');while(!stopping){try{const q=new URLSearchParams({limit:'100',timeout:'30',types:'message_created,message_callback,bot_started,bot_stopped'});if(state.marker!=null)q.set('marker',String(state.marker));const d=await max('GET',`/updates?${q}`);for(const u of d.updates||[])try{await onUpdate(u)}catch(e){log('update:',e.message)}if(d.marker!=null){state.marker=d.marker;saveState()}}catch(e){log('poll:',e.message);await sleep(3000)}}}
async function snap(p,d){if(p.role==='teacher'&&p.teacher){const a=await teacherChanges(d,p.teacher);return{kind:'teacher',rows:a,fp:hash(a.map(x=>[x.lesson,x.className,x.subject,x.room,x.status,x.oldClass,x.oldSubject,x.oldRoom]))}}if(p.role==='student'&&p.className){const a=await studentChanges(d,p.className);return{kind:'student',rows:a,fp:hash(a.map(x=>[x.lesson,x.change,x.note]))}}return{kind:'none',rows:[],fp:hash([])}}
async function notifyProfile(uid,p,d,s){if(s.kind==='teacher'){let t=`**Изменения в расписании · ${ruDate(d)}**\n_${esc(p.teacher)}_\n\n`;t+=s.rows.length?s.rows.map(x=>x.status==='cancelled'?`**${x.lesson} урок** — ОКНО${x.oldClass?` · было ${esc(x.oldClass)} ${esc(x.oldSubject||'')}`:''}`:`**${x.lesson} урок** — ${esc(x.className)} · ${esc(x.subject||'')}${x.room?` · каб. ${esc(x.room)}`:''}`).join('\n'):'Ранее опубликованные изменения для вас отменены. Работайте по основному расписанию.';t+=`\n\n_Обновлено ${new Intl.DateTimeFormat('ru-RU',{timeZone:TZ,hour:'2-digit',minute:'2-digit'}).format(new Date())}_`;return send(uid,t,[[cb('✓ Увидел',`seen:${d}`)],[cb('Открыть сегодня','today')]],true)}if(s.kind==='student'){let t=`**Обновилось расписание ${esc(p.className)} · ${ruDate(d)}**\n\n`;t+=s.rows.length?s.rows.map(x=>`**${x.lesson} урок** — ${esc(x.change)}${x.note?` · ${esc(x.note)}`:''}`).join('\n'):'Ранее опубликованные изменения отменены. Действует основное расписание.';return send(uid,t,[[cb('Показать весь день',d===moscowIso()?'today':'tomorrow')],[cb('Главное меню','home')]],true)}}
async function notifyNotice(uid,n){const pref=n.level==='urgent'?'❗ **Срочное оповещение**':n.level==='important'?'⚠ **Важное оповещение**':'**Оповещение школы**',rows=[];if(n.url)rows.push([link(n.buttonText||'Подробнее',n.url)]);else if(n.files?.[0]?.url)rows.push([link('Открыть файл',n.files[0].url)]);rows.push([cb('Оповещения','notices')]);return send(uid,`${pref}\n\n**${esc(n.title||'Сообщение')}**\n${esc(n.text||'')}`,rows,true)}
async function watch(){while(!stopping){try{sheetCache.clear();const d=moscowIso();for(const[uid,p]of Object.entries(state.profiles).filter(([,p])=>p.role&&p.notifications!==false)){try{const s=await snap(p,d);state.delivery[uid]||={};const prev=state.delivery[uid][d];if(!prev)state.delivery[uid][d]=s.fp;else if(prev!==s.fp){await notifyProfile(uid,p,d,s);state.delivery[uid][d]=s.fp;await sleep(600)}const a=await notices(p.role==='teacher'?'teachers':'students');state.noticeSeen[uid]||=[];const seenSet=new Set(state.noticeSeen[uid]);if(!state.notificationPrimed)a.forEach(n=>seenSet.add(n.id||hash(n)));else for(const n of a){const id=n.id||hash(n);if(!seenSet.has(id)){await notifyNotice(uid,n);seenSet.add(id);await sleep(600)}}state.noticeSeen[uid]=[...seenSet].slice(-200)}catch(e){log('notify',uid,e.message)}}state.notificationPrimed=true;saveState()}catch(e){log('watch:',e.message)}await sleep(CHECK_SECONDS*1000)}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function start(){const me=await max('GET','/me');log('Bot connected:',me.first_name||me.name||me.username||me.user_id);await siteCfg();const[t,c]=await Promise.all([teachers(),classes()]);log(`School data: ${t.length} teachers, ${c.length} classes`);Promise.all([poll(),watch()]).catch(e=>{console.error(e);process.exit(1)})}
process.on('SIGTERM',()=>{stopping=true;saveState()});process.on('SIGINT',()=>{stopping=true;saveState();setTimeout(()=>process.exit(0),300)});start().catch(e=>{console.error(e.stack||e.message);process.exit(1)});
