const MGMT_SHEETS = Object.freeze({
  absences: 'Отсутствия_учителей',
  journal: 'Журнал_замен',
  drafts: 'Черновики_дней',
  seen: 'Просмотры_учителей',
  notices: 'Оповещения',
  settings: 'Настройки_сайта'
});

function ensureManagementSheets_() {
  ensureMgmtSheet_(MGMT_SHEETS.absences, ['ID','С','По','Учитель','Причина','Комментарий','Создано'], true);
  ensureMgmtSheet_(MGMT_SHEETS.journal, ['Дата','Урок','Класс','Предмет','Кабинет','Основной учитель','Заменяющий учитель','Тип','Опубликовано'], true);
  ensureMgmtSheet_(MGMT_SHEETS.drafts, ['Дата','Обновлено','Учителя JSON','Ученики JSON'], true);
  ensureMgmtSheet_(MGMT_SHEETS.seen, ['Дата','Учитель','Просмотрено','Ключ устройства'], true);
  ensureMgmtSheet_(MGMT_SHEETS.notices, ['ID','Опубликовано','Заголовок','Текст','Тип','Начало','Окончание','Картинка','Файлы JSON','Текст кнопки','Ссылка','Аудитория','Активно'], false);
  const settings = ensureMgmtSheet_(MGMT_SHEETS.settings, ['Ключ','Значение','Обновлено'], true);
  upsertSetting_(settings, 'appsScriptUrl', ScriptApp.getService().getUrl() || '');
  return true;
}
function ensureMgmtSheet_(name, headers, hidden) { const ss=getSpreadsheet_(); let sh=ss.getSheetByName(name); if(!sh){sh=ss.insertSheet(name);sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);if(hidden)sh.hideSheet();} return sh; }
function upsertSetting_(sheet,key,value){const vals=sheet.getDataRange().getValues();for(let i=1;i<vals.length;i++){if(String(vals[i][0]||'')===key){sheet.getRange(i+1,2,1,2).setValues([[value,new Date()]]);return;}}sheet.appendRow([key,value,new Date()]);}

function getTeacherAbsences(token,dateIso){assertSession_(token);validateIsoDate_(dateIso);ensureManagementSheets_();const vals=getSpreadsheet_().getSheetByName(MGMT_SHEETS.absences).getDataRange().getValues();return vals.slice(1).filter(r=>{const f=normalizeDate_(r[1]),t=normalizeDate_(r[2]);return f&&t&&f<=dateIso&&dateIso<=t;}).map(r=>({id:String(r[0]||''),from:normalizeDate_(r[1]),to:normalizeDate_(r[2]),teacher:String(r[3]||'').trim(),reason:String(r[4]||''),comment:String(r[5]||'')}));}
function listTeacherAbsences(token,limit){assertSession_(token);ensureManagementSheets_();const vals=getSpreadsheet_().getSheetByName(MGMT_SHEETS.absences).getDataRange().getValues();return vals.slice(1).filter(r=>r.some(Boolean)).reverse().slice(0,Math.max(1,Math.min(Number(limit)||100,300))).map(r=>({id:String(r[0]||''),from:normalizeDate_(r[1]),to:normalizeDate_(r[2]),teacher:String(r[3]||''),reason:String(r[4]||''),comment:String(r[5]||'')}));}
function saveTeacherAbsence(token,item){assertSession_(token);ensureManagementSheets_();const teacher=String(item&&item.teacher||'').trim(),from=normalizeDate_(item&&item.from),to=normalizeDate_(item&&item.to);if(!teacher||!from||!to)throw new Error('Укажите учителя и период отсутствия');if(to<from)throw new Error('Дата окончания раньше даты начала');const sh=getSpreadsheet_().getSheetByName(MGMT_SHEETS.absences),id=String(item&&item.id||'')||Utilities.getUuid(),vals=sh.getDataRange().getValues();for(let i=1;i<vals.length;i++)if(String(vals[i][0]||'')===id){sh.getRange(i+1,1,1,7).setValues([[id,formatRuDate_(from),formatRuDate_(to),teacher,String(item.reason||''),String(item.comment||''),vals[i][6]||new Date()]]);return{id:id};}sh.appendRow([id,formatRuDate_(from),formatRuDate_(to),teacher,String(item.reason||''),String(item.comment||''),new Date()]);return{id:id};}
function deleteTeacherAbsence(token,id){assertSession_(token);ensureManagementSheets_();const sh=getSpreadsheet_().getSheetByName(MGMT_SHEETS.absences),vals=sh.getDataRange().getValues();for(let i=1;i<vals.length;i++)if(String(vals[i][0]||'')===String(id||'')){sh.deleteRow(i+1);return true;}return false;}

function saveAdminDraft(token,dateIso,teacherEdits,studentChanges){assertSession_(token);validateIsoDate_(dateIso);ensureManagementSheets_();const sh=getSpreadsheet_().getSheetByName(MGMT_SHEETS.drafts),vals=sh.getDataRange().getValues(),row=[formatRuDate_(dateIso),new Date(),JSON.stringify(teacherEdits||[]),JSON.stringify(studentChanges||[])];for(let i=1;i<vals.length;i++)if(normalizeDate_(vals[i][0])===dateIso){sh.getRange(i+1,1,1,4).setValues([row]);return{savedAt:Utilities.formatDate(new Date(),CONFIG.timeZone,'HH:mm:ss')};}sh.appendRow(row);return{savedAt:Utilities.formatDate(new Date(),CONFIG.timeZone,'HH:mm:ss')};}
function getAdminDraft(token,dateIso){assertSession_(token);validateIsoDate_(dateIso);ensureManagementSheets_();const vals=getSpreadsheet_().getSheetByName(MGMT_SHEETS.drafts).getDataRange().getValues(),row=vals.slice(1).find(r=>normalizeDate_(r[0])===dateIso);if(!row)return null;return{date:dateIso,savedAt:row[1] instanceof Date?Utilities.formatDate(row[1],CONFIG.timeZone,'dd.MM.yyyy HH:mm:ss'):String(row[1]||''),teacherEdits:safeJsonParse_(row[2],[]),studentChanges:safeJsonParse_(row[3],[])};}
function listAdminDrafts(token){assertSession_(token);ensureManagementSheets_();const vals=getSpreadsheet_().getSheetByName(MGMT_SHEETS.drafts).getDataRange().getValues();return vals.slice(1).filter(r=>r.some(Boolean)).map(r=>({date:normalizeDate_(r[0]),savedAt:r[1] instanceof Date?Utilities.formatDate(r[1],CONFIG.timeZone,'dd.MM.yyyy HH:mm:ss'):String(r[1]||''),teacherCount:safeJsonParse_(r[2],[]).length,studentCount:safeJsonParse_(r[3],[]).length})).sort((a,b)=>a.date.localeCompare(b.date));}
function deleteAdminDraft(token,dateIso){assertSession_(token);ensureManagementSheets_();const sh=getSpreadsheet_().getSheetByName(MGMT_SHEETS.drafts),vals=sh.getDataRange().getValues();for(let i=1;i<vals.length;i++)if(normalizeDate_(vals[i][0])===dateIso){sh.deleteRow(i+1);return true;}return false;}

function publishAdminDayManaged(token,dateIso,teacherEdits,studentChanges){assertSession_(token);const r=publishPayloadCore_(dateIso,teacherEdits,studentChanges,'Сейчас');recordReplacementJournal_(dateIso,teacherEdits);try{deleteAdminDraft(token,dateIso);}catch(_){}try{notifyMaxChanges_(dateIso,r.summary||{});}catch(_){}return r;}
function recordReplacementJournal_(dateIso,edits){ensureManagementSheets_();const built=buildEffectiveGrid_(dateIso,prepareTeacherEdits_(dateIso,edits||[])),baseByClass={};built.base.cells.forEach(c=>{if(c.className)baseByClass[c.className+'|'+c.lesson]=c;});const sh=getSpreadsheet_().getSheetByName(MGMT_SHEETS.journal),existing=sh.getDataRange().getValues(),preserved=existing.slice(1).filter(r=>normalizeDate_(r[0])!==dateIso),rows=[];built.effective.forEach(c=>{if(!c.className||!['changed','added','room'].includes(c.status))return;const original=baseByClass[c.className+'|'+c.lesson],originalTeacher=original?original.teacher:'';if(c.status==='room'&&originalTeacher===c.teacher)return;if(originalTeacher===c.teacher&&c.status!=='added')return;rows.push([formatRuDate_(dateIso),c.lesson,c.className,c.subject,c.room,originalTeacher,c.teacher,c.status,new Date()]);});rewriteBody_(sh,9,preserved.concat(rows));}
function getReplacementJournal(token,fromIso,toIso){assertSession_(token);ensureManagementSheets_();const from=normalizeDate_(fromIso),to=normalizeDate_(toIso),vals=getSpreadsheet_().getSheetByName(MGMT_SHEETS.journal).getDataRange().getValues();return vals.slice(1).filter(r=>{const d=normalizeDate_(r[0]);return d&&(!from||d>=from)&&(!to||d<=to);}).map(r=>({date:normalizeDate_(r[0]),lesson:Number(r[1])||0,className:String(r[2]||''),subject:String(r[3]||''),room:String(r[4]||''),originalTeacher:String(r[5]||''),replacementTeacher:String(r[6]||''),type:String(r[7]||'')}));}
function getReplacementTimesheet(token,monthIso){assertSession_(token);ensureManagementSheets_();const month=/^\d{4}-\d{2}$/.test(String(monthIso||''))?String(monthIso):isoToday_().slice(0,7),from=month+'-01',d=new Date(from+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);const rows=getReplacementJournal(token,from,d.toISOString().slice(0,10)),map={};rows.forEach(r=>{const t=r.replacementTeacher||'Не указан';if(!map[t])map[t]={teacher:t,count:0,lessons:[],classes:new Set(),subjects:new Set()};map[t].count++;map[t].lessons.push(r.date+' · '+r.lesson);if(r.className)map[t].classes.add(r.className);if(r.subject)map[t].subjects.add(r.subject);});return Object.values(map).map(x=>({teacher:x.teacher,count:x.count,classes:Array.from(x.classes).sort(),subjects:Array.from(x.subjects).sort(),lessons:x.lessons})).sort((a,b)=>b.count-a.count||localeCompare_(a.teacher,b.teacher));}

function markTeacherViewedPublic_(dateIso,teacher,deviceKey){if(!dateIso||!teacher)return false;ensureManagementSheets_();const sh=getSpreadsheet_().getSheetByName(MGMT_SHEETS.seen),vals=sh.getDataRange().getValues();for(let i=1;i<vals.length;i++)if(normalizeDate_(vals[i][0])===dateIso&&String(vals[i][1]||'')===teacher&&String(vals[i][3]||'')===String(deviceKey||'')){sh.getRange(i+1,3).setValue(new Date());return true;}sh.appendRow([formatRuDate_(dateIso),teacher,new Date(),String(deviceKey||'')]);return true;}
function getTeacherSeenSummary(token,dateIso){assertSession_(token);ensureManagementSheets_();const vals=getSpreadsheet_().getSheetByName(MGMT_SHEETS.seen).getDataRange().getValues(),out={};vals.slice(1).filter(r=>normalizeDate_(r[0])===dateIso).forEach(r=>{const t=String(r[1]||''),at=r[2] instanceof Date?Utilities.formatDate(r[2],CONFIG.timeZone,'HH:mm:ss'):String(r[2]||'');if(t)out[t]=at;});return out;}

function listNoticesAdmin(token){assertSession_(token);ensureManagementSheets_();const vals=getSpreadsheet_().getSheetByName(MGMT_SHEETS.notices).getDataRange().getValues();return vals.slice(1).filter(r=>r.some(Boolean)).reverse().map(r=>noticeRowToObject_(r));}
function noticeRowToObject_(r){return{id:String(r[0]||''),publishedAt:r[1] instanceof Date?Utilities.formatDate(r[1],CONFIG.timeZone,'dd.MM.yyyy HH:mm:ss'):String(r[1]||''),title:String(r[2]||''),text:String(r[3]||''),level:String(r[4]||'info'),start:normalizeDate_(r[5]),end:normalizeDate_(r[6]),image:String(r[7]||''),files:safeJsonParse_(r[8],[]),buttonText:String(r[9]||''),url:String(r[10]||''),audience:String(r[11]||'all'),active:String(r[12]||'').toLowerCase()!=='false'};}
function saveNotice(token,item){assertSession_(token);ensureManagementSheets_();const title=String(item&&item.title||'').trim(),text=String(item&&item.text||'').trim();if(!title&&!text)throw new Error('Заполните заголовок или текст');const id=String(item&&item.id||'')||Utilities.getUuid(),start=normalizeDate_(item&&item.start)||isoToday_(),end=normalizeDate_(item&&item.end)||start,row=[id,new Date(),title,text,String(item.level||'info'),formatRuDate_(start),formatRuDate_(end),String(item.image||''),JSON.stringify(item.files||[]),String(item.buttonText||''),String(item.url||''),String(item.audience||'all'),item.active===false?'false':'true'],sh=getSpreadsheet_().getSheetByName(MGMT_SHEETS.notices),vals=sh.getDataRange().getValues();for(let i=1;i<vals.length;i++)if(String(vals[i][0]||'')===id){sh.getRange(i+1,1,1,13).setValues([row]);maybeSendNoticeToMax_(item);return{id:id};}sh.appendRow(row);maybeSendNoticeToMax_(item);return{id:id};}
function deleteNotice(token,id){assertSession_(token);ensureManagementSheets_();const sh=getSpreadsheet_().getSheetByName(MGMT_SHEETS.notices),vals=sh.getDataRange().getValues();for(let i=1;i<vals.length;i++)if(String(vals[i][0]||'')===String(id||'')){sh.deleteRow(i+1);return true;}return false;}
function uploadNoticeFile(token,name,mimeType,base64Data){assertSession_(token);if(!base64Data)throw new Error('Файл пуст');const folder=getNoticeFolder_(),bytes=Utilities.base64Decode(String(base64Data).replace(/^data:[^,]+,/,'')),blob=Utilities.newBlob(bytes,String(mimeType||'application/octet-stream'),String(name||'file')),file=folder.createFile(blob);try{file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);}catch(_){}return{id:file.getId(),name:file.getName(),mimeType:file.getMimeType(),viewUrl:'https://drive.google.com/file/d/'+file.getId()+'/view',directUrl:'https://drive.google.com/uc?export=view&id='+file.getId()};}
function getNoticeFolder_(){const p=PropertiesService.getScriptProperties(),id=p.getProperty('NOTICE_FOLDER_ID');if(id){try{return DriveApp.getFolderById(id);}catch(_){}}const f=DriveApp.createFolder('СОШ20 — файлы оповещений');p.setProperty('NOTICE_FOLDER_ID',f.getId());return f;}

function getMaxSettings(token){assertSession_(token);const p=PropertiesService.getScriptProperties(),bot=p.getProperty('MAX_BOT_TOKEN')||'',chat=p.getProperty('MAX_CHAT_ID')||'';return{connected:!!bot,chatId:chat,tokenTail:bot?bot.slice(-6):'',webhookUrl:ScriptApp.getService().getUrl()||'',autoChanges:p.getProperty('MAX_AUTO_CHANGES')==='1'};}
function saveMaxSettings(token,botToken,chatId){assertSession_(token);const p=PropertiesService.getScriptProperties();if(String(botToken||'').trim())p.setProperty('MAX_BOT_TOKEN',String(botToken).trim());if(String(chatId||'').trim())p.setProperty('MAX_CHAT_ID',String(chatId).trim());return getMaxSettings(token);}
function sendMaxTest(token){assertSession_(token);return sendMaxMessage_('Тестовое сообщение от системы расписания МОУ СОШ №20. Подключение MAX работает.');}
function sendMaxMessage_(text,userId){const p=PropertiesService.getScriptProperties(),bot=p.getProperty('MAX_BOT_TOKEN'),chat=p.getProperty('MAX_CHAT_ID');if(!bot)throw new Error('Не задан MAX_BOT_TOKEN');const target=userId?('user_id='+encodeURIComponent(userId)):('chat_id='+encodeURIComponent(chat));if(!userId&&!chat)throw new Error('Не задан MAX_CHAT_ID');const r=UrlFetchApp.fetch('https://platform-api2.max.ru/messages?'+target,{method:'post',contentType:'application/json',headers:{Authorization:bot},payload:JSON.stringify({text:String(text||'')}),muteHttpExceptions:true}),code=r.getResponseCode();if(code<200||code>=300)throw new Error('MAX API '+code+': '+r.getContentText().slice(0,300));return{ok:true,code:code};}
function maybeSendNoticeToMax_(item){if(!item||!item.sendToMax)return;try{sendMaxMessage_((item.title?item.title+'\n\n':'')+String(item.text||'')+(item.url?'\n\n'+item.url:''));}catch(e){console.log('MAX notice:',e);}}
function notifyMaxChanges_(dateIso,summary){const p=PropertiesService.getScriptProperties();if(p.getProperty('MAX_AUTO_CHANGES')!=='1')return;try{sendMaxMessage_('Изменения в расписании на '+formatRuDate_(dateIso)+' опубликованы. Ученикам: '+(summary.studentChanges||0)+', изменений в сетке учителей: '+(summary.teacherEdits||0)+'.');}catch(e){console.log('MAX changes:',e);}}
function setMaxAutoChanges(token,enabled){assertSession_(token);PropertiesService.getScriptProperties().setProperty('MAX_AUTO_CHANGES',enabled?'1':'0');return true;}

function doPost(e){try{const p=e&&e.parameter?e.parameter:{};if(p.action==='markSeen'){markTeacherViewedPublic_(normalizeDate_(p.date),String(p.teacher||''),String(p.device||''));return ContentService.createTextOutput('ok').setMimeType(ContentService.MimeType.TEXT);}const body=e&&e.postData&&e.postData.contents?safeJsonParse_(e.postData.contents,{}):{};if(body&&body.update_type){handleMaxUpdate_(body);return ContentService.createTextOutput('ok').setMimeType(ContentService.MimeType.TEXT);}return ContentService.createTextOutput('ok').setMimeType(ContentService.MimeType.TEXT);}catch(err){return ContentService.createTextOutput('error').setMimeType(ContentService.MimeType.TEXT);}}
function handleMaxUpdate_(u){const msg=u.message||u.callback&&u.callback.message||{},sender=msg.sender||u.user||{},text=String(msg.body&&msg.body.text||msg.text||'').trim(),userId=sender.user_id||sender.userId||'';if(!userId||!text)return;if(/^\/(start|help)/i.test(text))return sendMaxMessage_('Команды:\n/today — изменения учеников на сегодня\n/teachers — количество изменений в сетке учителей\n/site — открыть сайт школы',userId);if(/^\/site/i.test(text))return sendMaxMessage_('https://sosh20tver.ru/',userId);if(/^\/today/i.test(text)){const d=isoToday_(),rows=readChangesForDate_(d),body=rows.length?rows.map(r=>r.className+' · '+r.lesson+' урок — '+r.change+(r.note?' ('+r.note+')':'')).join('\n'):'Изменений для учеников на сегодня нет.';return sendMaxMessage_(body,userId);}if(/^\/teachers/i.test(text)){const d=isoToday_(),edits=readTeacherEditsForDate_(d);return sendMaxMessage_('Сегодня в учительской сетке '+edits.length+' изменений.',userId);}}