from pathlib import Path
import re

p = Path('apps-script/Admin.html')
s = p.read_text(encoding='utf-8')
original = s

if 'student-print-modal' in s and '@page studentChanges' in s:
    print('Admin student print already patched')
    raise SystemExit(0)

old_print_css = '''    @media print{body{background:#fff}.wrap>*:not(.print-sheet),.toast,.modal-backdrop{display:none!important}.print-sheet{display:block!important;color:#000}.print-sheet h1{font-size:20px;margin:0 0 6px}.print-sheet .print-subtitle{margin:0 0 12px;font-size:12px}.print-sheet table{width:100%;border-collapse:collapse;font-size:11px}.print-sheet th,.print-sheet td{border:1px solid #000;padding:5px;text-align:left}.print-sheet th:nth-child(2),.print-sheet td:nth-child(2){text-align:center;width:55px}}'''
new_print_css = '''    @page studentChanges{size:A4 portrait;margin:6mm}
    .student-print-page{page:studentChanges;width:100%;min-height:283mm;display:flex;flex-direction:column;color:#172646;font-family:Arial,"Segoe UI",sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}
    .student-print-head{display:grid;grid-template-columns:18mm minmax(0,1fr) auto;gap:3mm;align-items:center;border-bottom:2px solid #183b74;padding-bottom:2.5mm;margin-bottom:2.5mm}.student-print-logo{width:15mm;height:15mm;object-fit:contain;border-radius:50%}.student-print-school{font-size:6.7pt;line-height:1.18;font-weight:800;text-transform:uppercase;color:#18345f}.student-print-school strong{display:block;font-size:12.5pt;letter-spacing:.02em;margin-top:1mm}.student-print-date{text-align:right;font-size:7pt;line-height:1.25;color:#4f607c}.student-print-date strong{display:block;font-size:10pt;color:#102552;margin-bottom:.8mm}
    .student-print-shift{margin-top:1.5mm}.student-print-shift-title{display:flex;align-items:center;justify-content:space-between;gap:3mm;border-radius:2.5mm;padding:1.6mm 2.2mm;margin-bottom:1.8mm;background:#eaf0ff;color:#17366d;font-weight:900;font-size:8pt;text-transform:uppercase;letter-spacing:.05em}.student-print-shift-title span{font-size:6pt;font-weight:700;text-transform:none;letter-spacing:0;color:#5b6d89}.student-shift-grid{display:grid;grid-template-columns:1fr 1fr;gap:2mm 2.5mm}.student-print-block{border:1px solid #b9c6db;border-radius:2mm;overflow:hidden;break-inside:avoid;background:#fff}.student-print-block-title{background:#f3f6fc;color:#17366d;text-align:center;font-size:6.6pt;font-weight:900;padding:1.1mm 1mm;border-bottom:1px solid #cbd5e5;text-transform:uppercase;letter-spacing:.04em}.student-print-block table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:6.1pt}.student-print-block th,.student-print-block td{border-right:1px solid #d7deea;border-bottom:1px solid #d7deea;text-align:center!important;vertical-align:middle;padding:.55mm .45mm;height:6.6mm;line-height:1.05;overflow:hidden}.student-print-block tr:last-child td{border-bottom:0}.student-print-block th:last-child,.student-print-block td:last-child{border-right:0}.student-print-block th{height:5.8mm;background:#fbfcff;color:#1d3866;font-size:6.2pt;font-weight:900}.student-print-block .lesson-col{width:7mm;color:#51617d;font-weight:900}.student-change{display:flex;min-height:5.1mm;align-items:center;justify-content:center;text-align:center;font-weight:800;color:#152a50;overflow-wrap:anywhere;word-break:break-word}.student-change.cancel{color:#a32632;font-weight:950}.student-change.room{color:#875b00}.student-change.long{font-size:5.35pt;line-height:1.02}.student-change small{display:block;font-size:4.8pt;font-weight:600;color:#6c7890;margin-top:.25mm}.student-print-footer{margin-top:auto;padding-top:2mm;border-top:1px solid #cfd8e7;display:flex;justify-content:space-between;gap:4mm;color:#69768e;font-size:5.7pt;line-height:1.25}.student-print-footer strong{color:#40516e}.student-print-legend{display:flex;gap:3mm;flex-wrap:wrap}.student-print-legend span:before{content:"";display:inline-block;width:2mm;height:2mm;border-radius:.5mm;margin-right:.8mm;vertical-align:middle}.student-print-legend .lg-cancel:before{background:#f4c7cb}.student-print-legend .lg-change:before{background:#d9e4ff}.student-print-legend .lg-room:before{background:#f6e7b3}
    @media print{body{background:#fff}.wrap>*:not(.print-sheet),.toast,.modal-backdrop{display:none!important}.print-sheet{display:block!important;color:#000}.print-sheet h1{font-size:20px;margin:0 0 6px}.print-sheet .print-subtitle{margin:0 0 12px;font-size:12px}.print-sheet table{width:100%;border-collapse:collapse;font-size:11px}.print-sheet th,.print-sheet td{border:1px solid #000;padding:5px;text-align:left}.print-sheet th:nth-child(2),.print-sheet td:nth-child(2){text-align:center;width:55px}.print-sheet:has(.student-print-page){width:100%;margin:0;padding:0}.print-sheet .student-print-page table{font-size:6.1pt}.print-sheet .student-print-page th,.print-sheet .student-print-page td{padding:.55mm .45mm;text-align:center;border-color:#d7deea}}'''
if old_print_css not in s:
    raise SystemExit('Print CSS target not found')
s = s.replace(old_print_css, new_print_css, 1)

photo_needle = '<div class="modal-backdrop" id="photo-modal" hidden>'
modal = '''<div class="modal-backdrop" id="student-print-modal" hidden><div class="modal"><div class="modal-head"><h3>Печать изменений для учеников</h3><p class="muted">Форма рассчитана на один лист А4 в книжной ориентации. При выборе обеих смен 1-я смена печатается сверху, 2-я — ниже.</p></div><div class="modal-body"><div class="wide section-mini"><h4>Что печатать</h4><div class="item-actions"><button class="btn" data-student-print-scope="both">Обе смены · 1 лист А4</button><button class="btn quiet" data-student-print-scope="first">Только 1 смена</button><button class="btn quiet" data-student-print-scope="second">Только 2 смена</button></div></div><div class="wide hint">Совет: в окне печати оставьте масштаб 100%. Если браузер добавляет свои адрес и дату, отключите «Колонтитулы» в дополнительных настройках печати.</div></div><div class="modal-actions"><button class="btn quiet" id="student-print-close">Закрыть</button></div></div></div>\n\n'''
if photo_needle not in s:
    raise SystemExit('Student print modal target not found')
s = s.replace(photo_needle, modal + photo_needle, 1)

pattern = r"function buildStudentPrint\(changes=finalChanges\(\)\)\{.*?\}\nfunction printMode\(mode\)\{.*?\}"
new_funcs = r'''function buildStudentPrintSimple(changes=finalChanges()){const rows=changes.map(x=>`<tr><td>${esc(x.className)}</td><td>${x.lesson}</td><td>${esc(x.change)}${x.note?' — '+esc(x.note):''}</td></tr>`).join('');return`<h1>Изменения для учеников</h1><p class="print-subtitle">${esc($('#day-label').textContent)}</p>${changes.length?`<table><tr><th>Класс</th><th>Урок</th><th>Изменение</th></tr>${rows}</table>`:'<p>Изменений для учеников нет.</p>'}`}
function printDateRu(iso){try{return new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(iso+'T12:00:00+03:00'))}catch(_){return iso}}
function printStamp(){return new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date()).replace(',',' ·')}
function classifyStudentPrintChange(x){const raw=String(x.change||'').trim(),low=raw.toLowerCase();if(/^отмен/.test(low))return{type:'cancel',html:'ОТМЕНА'};const long=raw.length>32?' long':'';const roomOnly=/^(?:каб(?:инет)?\s*)?\d{3}$/i.test(raw);return{type:roomOnly?'room':'change',html:`${esc(raw)}${x.note?`<small>${esc(x.note)}</small>`:''}`,long}}
function studentPrintBlock(title,classes,lessons,map){const head=classes.map(c=>`<th>${esc(c)}</th>`).join(''),rows=lessons.map(l=>`<tr><td class="lesson-col">${l}</td>${classes.map(c=>{const x=map.get(key(c,l));if(!x)return'<td></td>';const v=classifyStudentPrintChange(x);return`<td><div class="student-change ${v.type}${v.long||''}">${v.html}</div></td>`}).join('')}</tr>`).join('');return`<section class="student-print-block"><div class="student-print-block-title">${esc(title)}</div><table><thead><tr><th class="lesson-col">№</th>${head}</tr></thead><tbody>${rows}</tbody></table></section>`}
function buildStudentPrint(changes=finalChanges(),scope='both'){const map=new Map(changes.map(x=>[key(x.className,x.lesson),x])),firstLessons=[1,2,3,4,5,6,7,8],secondLessons=[4,5,6,7,8,9,10,11,12];const firstBlocks=[['5 классы',['5А','5Б','5В','5И']],['6 классы',['6А','6Б','6И','6К']],['9 классы',['9А','9Б','9В','9Г']],['10–11 классы',['10А','11А']]],secondBlocks=[['7 классы',['7А','7Б','7В']],['8 классы',['8А','8Б','8В','8Г']]];const firstCount=changes.filter(x=>/^(5|6|9|10|11)/.test(x.className)).length,secondCount=changes.filter(x=>/^(7|8)/.test(x.className)).length;const shift=(name,blocks,lessons,count)=>`<section class="student-print-shift"><div class="student-print-shift-title"><strong>${name}</strong><span>${count?`изменений: ${count}`:'изменений нет'}</span></div><div class="student-shift-grid">${blocks.map(([t,c])=>studentPrintBlock(t,c,lessons,map)).join('')}</div></section>`;const date=printDateRu($('#date').value),content=(scope==='first'?shift('1 смена',firstBlocks,firstLessons,firstCount):scope==='second'?shift('2 смена · уроки 4–12',secondBlocks,secondLessons,secondCount):shift('1 смена',firstBlocks,firstLessons,firstCount)+shift('2 смена · уроки 4–12',secondBlocks,secondLessons,secondCount));return`<div class="student-print-page"><header class="student-print-head"><img class="student-print-logo" src="https://sosh20tver.ru/assets/school-logo.jpg" alt="Логотип"><div class="student-print-school">Муниципальное общеобразовательное учреждение<br>«Средняя общеобразовательная школа № 20» имени Ивана Андреевича Рыбалко<strong>Изменения в расписании</strong></div><div class="student-print-date"><strong>${esc(date)}</strong>${scope==='both'?'1 и 2 смена':scope==='first'?'1 смена':'2 смена'}</div></header>${content}<footer class="student-print-footer"><div><strong>Актуально на момент печати.</strong><br>Сформировано: ${esc(printStamp())}</div><div class="student-print-legend"><span class="lg-cancel">отмена</span><span class="lg-change">замена / новый урок</span><span class="lg-room">кабинет</span></div><div>МОУ СОШ № 20 · 1 / 1</div></footer></div>`}
function openStudentPrintOptions(){$('#student-print-modal').hidden=false}
function printMode(mode,scope='both'){if(mode==='students'){$('#student-print-modal').hidden=true;$('#print-sheet').innerHTML=buildStudentPrint(finalChanges(),scope)}else $('#print-sheet').innerHTML=buildTeacherPrint();setTimeout(()=>window.print(),60)}'''
s, n = re.subn(pattern, lambda m: new_funcs, s, count=1, flags=re.S)
if n != 1:
    raise SystemExit(f'Student print function target not found: {n}')

s = s.replace('${buildStudentPrint(r.studentChanges)}', '${buildStudentPrintSimple(r.studentChanges)}')
old_handlers = "$('#print-students-button').onclick=()=>printMode('students');$('#print-students-inline').onclick=()=>printMode('students');"
new_handlers = "$('#print-students-button').onclick=openStudentPrintOptions;$('#print-students-inline').onclick=openStudentPrintOptions;$('#student-print-close').onclick=()=>$('#student-print-modal').hidden=true;$('#student-print-modal').onclick=e=>{const b=e.target.closest('[data-student-print-scope]');if(b)printMode('students',b.dataset.studentPrintScope)};"
if old_handlers not in s:
    raise SystemExit('Student print handlers target not found')
s = s.replace(old_handlers, new_handlers, 1)

if s == original:
    raise SystemExit('No changes produced')
p.write_text(s, encoding='utf-8')
print('Admin.html patched for portrait A4 student print')
